POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Vídeo node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}


###

GET http://localhost:3333/videos?search=Node

###

PUT http://localhost:3333/videos/a3a76bf7-cf65-4aea-9569-449a55acf7ef
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}


###

DELETE http://localhost:3333/videos/a3a76bf7-cf65-4aea-9569-449a55acf7ef
